language: python
python:
  - 2.7
  - 3.6

services:
  - docker

install:
  - docker build --no-cache -t bdbstudios/ansible-builder .

script:
  - docker run --rm bdbstudios/ansible-builder bash -c 'python /home/tools/tests/tests.py'
